import { useEffect, useState } from 'react';
import { getPurchaseOrders, approvePurchaseOrder, rejectPurchaseOrder } from '../services/purchaseOrderService';
import { PurchaseOrder } from '../types';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { ClipboardList, Clock, CheckCircle2, Truck, PackageCheck, Loader2, XCircle } from 'lucide-react';
import { formatNumber, formatDate } from '../utils/formatters';
import { motion, Variants } from 'framer-motion';

const containerVariants: Variants = {
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { staggerChildren: 0.1 } },
};
const itemVariants: Variants = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 300, damping: 24 } },
};

type FilterTab = 'All' | 'Pending Approval' | 'Approved' | 'Shipped' | 'Delivered' | 'Rejected';

const statusBadge = (status: PurchaseOrder['status']) => {
  const map: Record<PurchaseOrder['status'], 'warning' | 'info' | 'error' | 'success' | 'neutral'> = {
    'Pending Approval': 'warning',
    'Approved': 'info',
    'Rejected': 'error',
    'Shipped': 'neutral',
    'Delivered': 'success',
  };
  return <Badge variant={map[status]}>{status}</Badge>;
};

const PurchaseOrders = () => {
  const [orders, setOrders] = useState<PurchaseOrder[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<FilterTab>('All');
  const [processingId, setProcessingId] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try { setOrders(await getPurchaseOrders()); }
      catch (e) { console.error(e); }
      finally { setIsLoading(false); }
    };
    fetchData();
  }, []);

  const handleApprove = async (id: string) => {
    setProcessingId(id);
    try {
      await approvePurchaseOrder(id);
      setOrders(prev => prev.map(o => o.id === id ? { ...o, status: 'Approved' as const } : o));
    } finally { setProcessingId(null); }
  };

  const handleReject = async (id: string) => {
    setProcessingId(id);
    try {
      await rejectPurchaseOrder(id);
      setOrders(prev => prev.map(o => o.id === id ? { ...o, status: 'Rejected' as const } : o));
    } finally { setProcessingId(null); }
  };

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center p-12">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600" />
      </div>
    );
  }

  const tabs: FilterTab[] = ['All', 'Pending Approval', 'Approved', 'Shipped', 'Delivered', 'Rejected'];
  const filtered = activeTab === 'All' ? orders : orders.filter(o => o.status === activeTab);

  const counts = {
    total: orders.length,
    pending: orders.filter(o => o.status === 'Pending Approval').length,
    approved: orders.filter(o => o.status === 'Approved').length,
    delivered: orders.filter(o => o.status === 'Delivered').length,
  };

  return (
    <motion.div variants={containerVariants} initial="hidden" animate="show" className="space-y-6">
      <motion.div variants={itemVariants}>
        <div>
          <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Purchase Order Management</h1>
          <p className="text-sm text-slate-500 mt-1">Track and manage all purchase orders generated by the system.</p>
        </div>
      </motion.div>

      {/* Summary Cards */}
      <motion.div variants={itemVariants} className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
        <Card hoverEffect className="border-l-4 border-l-primary-500">
          <CardContent className="p-5 flex items-center justify-between">
            <div><p className="text-sm font-medium text-slate-500">Total Orders</p><h4 className="text-3xl font-bold text-slate-900 mt-1">{counts.total}</h4></div>
            <div className="p-3 bg-primary-50 text-primary-600 rounded-2xl"><ClipboardList className="h-6 w-6" /></div>
          </CardContent>
        </Card>
        <Card hoverEffect>
          <CardContent className="p-5 flex items-center justify-between">
            <div><p className="text-sm font-medium text-slate-500">Pending Approval</p><h4 className="text-3xl font-bold text-slate-900 mt-1">{counts.pending}</h4></div>
            <div className="p-3 bg-warning-50 text-warning-500 rounded-2xl"><Clock className="h-6 w-6" /></div>
          </CardContent>
        </Card>
        <Card hoverEffect>
          <CardContent className="p-5 flex items-center justify-between">
            <div><p className="text-sm font-medium text-slate-500">Approved</p><h4 className="text-3xl font-bold text-slate-900 mt-1">{counts.approved}</h4></div>
            <div className="p-3 bg-success-50 text-success-500 rounded-2xl"><CheckCircle2 className="h-6 w-6" /></div>
          </CardContent>
        </Card>
        <Card hoverEffect>
          <CardContent className="p-5 flex items-center justify-between">
            <div><p className="text-sm font-medium text-slate-500">Delivered</p><h4 className="text-3xl font-bold text-slate-900 mt-1">{counts.delivered}</h4></div>
            <div className="p-3 bg-info-50 text-info-500 rounded-2xl"><PackageCheck className="h-6 w-6" /></div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Filter Tabs & Table */}
      <motion.div variants={itemVariants}>
        <Card noPadding hoverEffect>
          <CardHeader className="px-6 py-5">
            <CardTitle>Order History</CardTitle>
          </CardHeader>
          <div className="px-6 pb-3 flex flex-wrap gap-2">
            {tabs.map(tab => (
              <button key={tab} onClick={() => setActiveTab(tab)}
                className={`px-4 py-1.5 rounded-2xl text-xs font-semibold transition-colors ${activeTab === tab ? 'app-button-primary text-white' : 'app-button-secondary text-slate-600 hover:text-white'}`}
              >{tab}</button>
            ))}
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="app-table-head text-slate-500 font-medium">
                <tr>
                  <th className="px-6 py-4 uppercase tracking-wider text-xs">PO ID</th>
                  <th className="px-6 py-4 uppercase tracking-wider text-xs">SKU</th>
                  <th className="px-6 py-4 uppercase tracking-wider text-xs text-right">Quantity</th>
                  <th className="px-6 py-4 uppercase tracking-wider text-xs">Supplier</th>
                  <th className="px-6 py-4 uppercase tracking-wider text-xs">Order Date</th>
                  <th className="px-6 py-4 uppercase tracking-wider text-xs">Expected Delivery</th>
                  <th className="px-6 py-4 uppercase tracking-wider text-xs text-center">Status</th>
                  <th className="px-6 py-4 uppercase tracking-wider text-xs text-center">Actions</th>
                </tr>
              </thead>
              <tbody className="app-table-body divide-y divide-slate-100/80">
                {filtered.length === 0 ? (
                  <tr><td colSpan={8} className="px-6 py-8 text-center text-slate-500">No orders found.</td></tr>
                ) : (
                  filtered.map(o => (
                    <tr key={o.id} className="app-table-row">
                      <td className="px-6 py-4 font-bold text-navy-900">{o.id}</td>
                      <td className="px-6 py-4 text-slate-600 font-medium">{o.sku}</td>
                      <td className="px-6 py-4 text-right font-semibold text-slate-900">{formatNumber(o.quantity)}</td>
                      <td className="px-6 py-4 text-slate-600">{o.supplier}</td>
                      <td className="px-6 py-4 text-slate-600">{formatDate(o.order_date)}</td>
                      <td className="px-6 py-4 text-slate-600">{formatDate(o.expected_delivery)}</td>
                      <td className="px-6 py-4 text-center">{statusBadge(o.status)}</td>
                      <td className="px-6 py-4">
                        {o.status === 'Pending Approval' ? (
                          <div className="flex items-center justify-center space-x-2">
                            <button onClick={() => handleApprove(o.id)} disabled={processingId === o.id}
                              className="rounded-xl bg-success-50/90 p-1.5 text-success-600 shadow-sm transition-colors hover:bg-success-100 disabled:opacity-50"
                              title="Approve">
                              {processingId === o.id ? <Loader2 className="h-5 w-5 animate-spin" /> : <CheckCircle2 className="h-5 w-5" />}
                            </button>
                            <button onClick={() => handleReject(o.id)} disabled={processingId === o.id}
                              className="rounded-xl bg-danger-50/90 p-1.5 text-danger-600 shadow-sm transition-colors hover:bg-danger-100 disabled:opacity-50"
                              title="Reject">
                              <XCircle className="h-5 w-5" />
                            </button>
                          </div>
                        ) : (
                          <div className="flex justify-center">
                            <Truck className="h-4 w-4 text-slate-400" />
                          </div>
                        )}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </Card>
      </motion.div>
    </motion.div>
  );
};

export default PurchaseOrders;
